# Generated by Django 2.1 on 2018-08-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('telegram_chat_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('telegram_update_id', models.BigIntegerField()),
                ('update', models.TextField()),
                ('type', models.CharField(choices=[('video', 'video'), ('photo', 'photo'), ('document', 'document'), ('audio', 'audio'), ('animation', 'animation'), ('sticker', 'sticker'), ('video_note', 'video_note'), ('contact', 'contact'), ('location', 'location'), ('venue', 'venue'), ('text', 'text')], default='text', max_length=30)),
                ('message_time', models.DateTimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='django_telegram_blog.Blog')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
