# Generated by Django 2.1 on 2018-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='telegram_big_photo_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='telegram_small_photo_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('private', 'private'), ('group', 'group'), ('supergroup', 'supergroup'), ('channel', 'channel')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('voice', 'voice'), ('photo', 'photo'), ('document', 'document'), ('audio', 'audio'), ('animation', 'animation'), ('sticker', 'sticker'), ('video_note', 'video_note'), ('contact', 'contact'), ('location', 'location'), ('venue', 'venue'), ('text', 'text')], default='text', max_length=30),
        ),
    ]
