# Generated by Django 2.1 on 2018-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_blog', '0002_auto_20180825_0722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='telegram_update_id',
        ),
        migrations.AddField(
            model_name='entry',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='telegram_message_id',
            field=models.BigIntegerField(default=666),
            preserve_default=False,
        ),
    ]
