# Generated by Django 2.1 on 2018-08-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_blog', '0003_auto_20180825_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='update',
            new_name='message_json',
        ),
    ]
