# Generated by Django 2.1 on 2018-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_blog', '0004_auto_20180825_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='extension',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
