# Generated by Django 2.1 on 2018-08-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_blog', '0005_entry_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extension',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
